name: CI
on: [pull_request, push]
jobs:
  android-ci:
    runs-on: macos-12

    steps:
      - name: Set up JDK 17
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Checkout the code
      - uses: actions/checkout@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build the app
        run: ./gradlew build
      - name: Unit tests
        run: bash ./gradlew test --stacktrace